### ISSUE TITLE
Tutorials for CDM2024

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith-tutorials#19]
## Tutorials

1. Static without faults: `reverse-2d`
  1. meshing
  2. gravity (start with coarse mesh and basis order=1, refine, coarse with basis order=2)
  3. surface loading
2. Quasi-static with prescribed slip: `reverse-2d`
  1. one fault
  2. two faults with different origin times
3. troubleshooting
4. Advanced meshing with Gmsh
  1. 2D with nonplanar embedded fault
  2. 3D with nonplanar embedded fault
5. Quasi-static with prescribed slip: `subduction-2d`
  1. Interseismic
  2. Eq cycle with prescribed slip
6. Static Green's functions: `strikeslip-2d`

## To-do

- [ ] New slides for `reverse-2d` (meshing, gravity, surface loading) and discretization steps
- [ ] New or updated slides for `reverse-2d` (one fault, two faults with different origin times)
- [ ] Update slides for troubleshooting`
- [ ] New slides for advanced meshing
- [ ] New slides for quasi-static with prescribed slip (interseismic and eq cycle)
- [ ] Update slides for static Green's functions

**Comment by baagaard-usgs** [comment]
Terrain meshing: https://gitlab.onelab.info/gmsh/gmsh/blob/gmsh_4_12_2/tutorials/python/x2.py

**Comment by baagaard-usgs** [comment]
Running Cubit in a standalone Python script

```
#!python
import sys
# add Cubit libraries to your path
sys.path.append('/Applications/Cubit-15.4/Cubit.app/Contents/MacOS')
import cubit
cubit.init(['cubit','-nojournal'])
```

**Comment by baagaard-usgs** [comment]
## PyVista notes

[Mesh Quality](https://docs.pyvista.org/version/stable/examples/01-filter/mesh-quality.html)

[Slide widget](https://docs.pyvista.org/version/stable/examples/03-widgets/slider-bar-widget.html) for selecting threshold in mesh quality.

[Checkbox widget](https://docs.pyvista.org/version/stable/examples/03-widgets/checkbox-widget) for selecting component.
